App         = "ChaosTF"
Description = "Automatically generated by ChaosTF"

job "aws" "ec2" {
  region = "us-east-1"
  config {
    tag   = "env:dev"
    chaos = "terminate"
    count = 1
  }
}

job "aws" "ec2" {
  region = "us-east-1"
  config {
    tag   = "env:dev"
    chaos = "terminate"
    count = 1
  }
}

